// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ClientsGet403Response
 */
export interface ApiV1ClientsGet403Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ClientsGet403Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ApiV1ClientsGet403Response interface.
 */
export function instanceOfApiV1ClientsGet403Response(value: object): value is ApiV1ClientsGet403Response {
    return true;
}

export function ApiV1ClientsGet403ResponseFromJSON(json: any): ApiV1ClientsGet403Response {
    return ApiV1ClientsGet403ResponseFromJSONTyped(json, false);
}

export function ApiV1ClientsGet403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ClientsGet403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ApiV1ClientsGet403ResponseToJSON(json: any): ApiV1ClientsGet403Response {
    return ApiV1ClientsGet403ResponseToJSONTyped(json, false);
}

export function ApiV1ClientsGet403ResponseToJSONTyped(value?: ApiV1ClientsGet403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

