// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner
 */
export interface ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner
     */
    type?: string;
}

/**
 * Check if a given object implements the ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner interface.
 */
export function instanceOfApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner(value: object): value is ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner {
    return true;
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSON(json: any): ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner {
    return ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSON(json: any): ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner {
    return ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSONTyped(value?: ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

