// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Client } from './Client';
import {
    ClientFromJSON,
    ClientFromJSONTyped,
    ClientToJSON,
    ClientToJSONTyped,
} from './Client';

/**
 * 
 * @export
 * @interface ApiV1ClientsGet200Response
 */
export interface ApiV1ClientsGet200Response {
    /**
     * 
     * @type {Array<Client>}
     * @memberof ApiV1ClientsGet200Response
     */
    data?: Array<Client>;
    /**
     * Pagination links
     * @type {object}
     * @memberof ApiV1ClientsGet200Response
     */
    links?: object;
    /**
     * Pagination metadata
     * @type {object}
     * @memberof ApiV1ClientsGet200Response
     */
    meta?: object;
}

/**
 * Check if a given object implements the ApiV1ClientsGet200Response interface.
 */
export function instanceOfApiV1ClientsGet200Response(value: object): value is ApiV1ClientsGet200Response {
    return true;
}

export function ApiV1ClientsGet200ResponseFromJSON(json: any): ApiV1ClientsGet200Response {
    return ApiV1ClientsGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1ClientsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ClientsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ClientFromJSON)),
        'links': json['links'] == null ? undefined : json['links'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function ApiV1ClientsGet200ResponseToJSON(json: any): ApiV1ClientsGet200Response {
    return ApiV1ClientsGet200ResponseToJSONTyped(json, false);
}

export function ApiV1ClientsGet200ResponseToJSONTyped(value?: ApiV1ClientsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ClientToJSON)),
        'links': value['links'],
        'meta': value['meta'],
    };
}

