// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientRegistry } from './ClientRegistry';
import {
    ClientRegistryFromJSON,
    ClientRegistryFromJSONTyped,
    ClientRegistryToJSON,
    ClientRegistryToJSONTyped,
} from './ClientRegistry';

/**
 * 
 * @export
 * @interface ApiV1ClientsClientIdRegistriesPost200Response
 */
export interface ApiV1ClientsClientIdRegistriesPost200Response {
    /**
     * 
     * @type {ClientRegistry}
     * @memberof ApiV1ClientsClientIdRegistriesPost200Response
     */
    data?: ClientRegistry;
}

/**
 * Check if a given object implements the ApiV1ClientsClientIdRegistriesPost200Response interface.
 */
export function instanceOfApiV1ClientsClientIdRegistriesPost200Response(value: object): value is ApiV1ClientsClientIdRegistriesPost200Response {
    return true;
}

export function ApiV1ClientsClientIdRegistriesPost200ResponseFromJSON(json: any): ApiV1ClientsClientIdRegistriesPost200Response {
    return ApiV1ClientsClientIdRegistriesPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1ClientsClientIdRegistriesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ClientsClientIdRegistriesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ClientRegistryFromJSON(json['data']),
    };
}

export function ApiV1ClientsClientIdRegistriesPost200ResponseToJSON(json: any): ApiV1ClientsClientIdRegistriesPost200Response {
    return ApiV1ClientsClientIdRegistriesPost200ResponseToJSONTyped(json, false);
}

export function ApiV1ClientsClientIdRegistriesPost200ResponseToJSONTyped(value?: ApiV1ClientsClientIdRegistriesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ClientRegistryToJSON(value['data']),
    };
}

