// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1UsersIdGet200ResponseIncludedInner } from './ApiV1UsersIdGet200ResponseIncludedInner';
import {
    ApiV1UsersIdGet200ResponseIncludedInnerFromJSON,
    ApiV1UsersIdGet200ResponseIncludedInnerFromJSONTyped,
    ApiV1UsersIdGet200ResponseIncludedInnerToJSON,
    ApiV1UsersIdGet200ResponseIncludedInnerToJSONTyped,
} from './ApiV1UsersIdGet200ResponseIncludedInner';
import type { ApiV1UsersIdGet200ResponseData } from './ApiV1UsersIdGet200ResponseData';
import {
    ApiV1UsersIdGet200ResponseDataFromJSON,
    ApiV1UsersIdGet200ResponseDataFromJSONTyped,
    ApiV1UsersIdGet200ResponseDataToJSON,
    ApiV1UsersIdGet200ResponseDataToJSONTyped,
} from './ApiV1UsersIdGet200ResponseData';

/**
 * 
 * @export
 * @interface ApiV1UsersIdGet200Response
 */
export interface ApiV1UsersIdGet200Response {
    /**
     * 
     * @type {ApiV1UsersIdGet200ResponseData}
     * @memberof ApiV1UsersIdGet200Response
     */
    data?: ApiV1UsersIdGet200ResponseData;
    /**
     * Included resources when using the include parameter
     * @type {Array<ApiV1UsersIdGet200ResponseIncludedInner>}
     * @memberof ApiV1UsersIdGet200Response
     */
    included?: Array<ApiV1UsersIdGet200ResponseIncludedInner>;
}

/**
 * Check if a given object implements the ApiV1UsersIdGet200Response interface.
 */
export function instanceOfApiV1UsersIdGet200Response(value: object): value is ApiV1UsersIdGet200Response {
    return true;
}

export function ApiV1UsersIdGet200ResponseFromJSON(json: any): ApiV1UsersIdGet200Response {
    return ApiV1UsersIdGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UsersIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ApiV1UsersIdGet200ResponseDataFromJSON(json['data']),
        'included': json['included'] == null ? undefined : ((json['included'] as Array<any>).map(ApiV1UsersIdGet200ResponseIncludedInnerFromJSON)),
    };
}

export function ApiV1UsersIdGet200ResponseToJSON(json: any): ApiV1UsersIdGet200Response {
    return ApiV1UsersIdGet200ResponseToJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseToJSONTyped(value?: ApiV1UsersIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ApiV1UsersIdGet200ResponseDataToJSON(value['data']),
        'included': value['included'] == null ? undefined : ((value['included'] as Array<any>).map(ApiV1UsersIdGet200ResponseIncludedInnerToJSON)),
    };
}

