// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RecoverPasswordPost200Response
 */
export interface ApiV1RecoverPasswordPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1RecoverPasswordPost200Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1RecoverPasswordPost200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the ApiV1RecoverPasswordPost200Response interface.
 */
export function instanceOfApiV1RecoverPasswordPost200Response(value: object): value is ApiV1RecoverPasswordPost200Response {
    return true;
}

export function ApiV1RecoverPasswordPost200ResponseFromJSON(json: any): ApiV1RecoverPasswordPost200Response {
    return ApiV1RecoverPasswordPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1RecoverPasswordPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RecoverPasswordPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ApiV1RecoverPasswordPost200ResponseToJSON(json: any): ApiV1RecoverPasswordPost200Response {
    return ApiV1RecoverPasswordPost200ResponseToJSONTyped(json, false);
}

export function ApiV1RecoverPasswordPost200ResponseToJSONTyped(value?: ApiV1RecoverPasswordPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

