// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ResetPasswordPost400Response
 */
export interface ApiV1ResetPasswordPost400Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ResetPasswordPost400Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ResetPasswordPost400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the ApiV1ResetPasswordPost400Response interface.
 */
export function instanceOfApiV1ResetPasswordPost400Response(value: object): value is ApiV1ResetPasswordPost400Response {
    return true;
}

export function ApiV1ResetPasswordPost400ResponseFromJSON(json: any): ApiV1ResetPasswordPost400Response {
    return ApiV1ResetPasswordPost400ResponseFromJSONTyped(json, false);
}

export function ApiV1ResetPasswordPost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ResetPasswordPost400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ApiV1ResetPasswordPost400ResponseToJSON(json: any): ApiV1ResetPasswordPost400Response {
    return ApiV1ResetPasswordPost400ResponseToJSONTyped(json, false);
}

export function ApiV1ResetPasswordPost400ResponseToJSONTyped(value?: ApiV1ResetPasswordPost400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
    };
}

