// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1SignUpPost200ResponseData } from './ApiV1SignUpPost200ResponseData';
import {
    ApiV1SignUpPost200ResponseDataFromJSON,
    ApiV1SignUpPost200ResponseDataFromJSONTyped,
    ApiV1SignUpPost200ResponseDataToJSON,
    ApiV1SignUpPost200ResponseDataToJSONTyped,
} from './ApiV1SignUpPost200ResponseData';

/**
 * 
 * @export
 * @interface ApiV1SignUpPost200Response
 */
export interface ApiV1SignUpPost200Response {
    /**
     * 
     * @type {ApiV1SignUpPost200ResponseData}
     * @memberof ApiV1SignUpPost200Response
     */
    data?: ApiV1SignUpPost200ResponseData;
}

/**
 * Check if a given object implements the ApiV1SignUpPost200Response interface.
 */
export function instanceOfApiV1SignUpPost200Response(value: object): value is ApiV1SignUpPost200Response {
    return true;
}

export function ApiV1SignUpPost200ResponseFromJSON(json: any): ApiV1SignUpPost200Response {
    return ApiV1SignUpPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1SignUpPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SignUpPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ApiV1SignUpPost200ResponseDataFromJSON(json['data']),
    };
}

export function ApiV1SignUpPost200ResponseToJSON(json: any): ApiV1SignUpPost200Response {
    return ApiV1SignUpPost200ResponseToJSONTyped(json, false);
}

export function ApiV1SignUpPost200ResponseToJSONTyped(value?: ApiV1SignUpPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ApiV1SignUpPost200ResponseDataToJSON(value['data']),
    };
}

