// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ClientsClientIdRegistriesGet200ResponseMeta
 */
export interface ApiV1ClientsClientIdRegistriesGet200ResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseMeta
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseMeta
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseMeta
     */
    lastPage?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseMeta
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseMeta
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseMeta
     */
    to?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseMeta
     */
    total?: number;
}

/**
 * Check if a given object implements the ApiV1ClientsClientIdRegistriesGet200ResponseMeta interface.
 */
export function instanceOfApiV1ClientsClientIdRegistriesGet200ResponseMeta(value: object): value is ApiV1ClientsClientIdRegistriesGet200ResponseMeta {
    return true;
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseMetaFromJSON(json: any): ApiV1ClientsClientIdRegistriesGet200ResponseMeta {
    return ApiV1ClientsClientIdRegistriesGet200ResponseMetaFromJSONTyped(json, false);
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ClientsClientIdRegistriesGet200ResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'from': json['from'] == null ? undefined : json['from'],
        'lastPage': json['last_page'] == null ? undefined : json['last_page'],
        'path': json['path'] == null ? undefined : json['path'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'to': json['to'] == null ? undefined : json['to'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseMetaToJSON(json: any): ApiV1ClientsClientIdRegistriesGet200ResponseMeta {
    return ApiV1ClientsClientIdRegistriesGet200ResponseMetaToJSONTyped(json, false);
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseMetaToJSONTyped(value?: ApiV1ClientsClientIdRegistriesGet200ResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'from': value['from'],
        'last_page': value['lastPage'],
        'path': value['path'],
        'per_page': value['perPage'],
        'to': value['to'],
        'total': value['total'],
    };
}

