// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SignUpPost200ResponseDataAttributes
 */
export interface ApiV1SignUpPost200ResponseDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SignUpPost200ResponseDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SignUpPost200ResponseDataAttributes
     */
    email?: string;
}

/**
 * Check if a given object implements the ApiV1SignUpPost200ResponseDataAttributes interface.
 */
export function instanceOfApiV1SignUpPost200ResponseDataAttributes(value: object): value is ApiV1SignUpPost200ResponseDataAttributes {
    return true;
}

export function ApiV1SignUpPost200ResponseDataAttributesFromJSON(json: any): ApiV1SignUpPost200ResponseDataAttributes {
    return ApiV1SignUpPost200ResponseDataAttributesFromJSONTyped(json, false);
}

export function ApiV1SignUpPost200ResponseDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SignUpPost200ResponseDataAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function ApiV1SignUpPost200ResponseDataAttributesToJSON(json: any): ApiV1SignUpPost200ResponseDataAttributes {
    return ApiV1SignUpPost200ResponseDataAttributesToJSONTyped(json, false);
}

export function ApiV1SignUpPost200ResponseDataAttributesToJSONTyped(value?: ApiV1SignUpPost200ResponseDataAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

