// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ResetPasswordPostRequest
 */
export interface ApiV1ResetPasswordPostRequest {
    /**
     * Password reset token
     * @type {string}
     * @memberof ApiV1ResetPasswordPostRequest
     */
    token: string;
    /**
     * User's email address
     * @type {string}
     * @memberof ApiV1ResetPasswordPostRequest
     */
    email: string;
    /**
     * New password
     * @type {string}
     * @memberof ApiV1ResetPasswordPostRequest
     */
    password: string;
    /**
     * Confirm new password
     * @type {string}
     * @memberof ApiV1ResetPasswordPostRequest
     */
    passwordConfirmation: string;
}

/**
 * Check if a given object implements the ApiV1ResetPasswordPostRequest interface.
 */
export function instanceOfApiV1ResetPasswordPostRequest(value: object): value is ApiV1ResetPasswordPostRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('passwordConfirmation' in value) || value['passwordConfirmation'] === undefined) return false;
    return true;
}

export function ApiV1ResetPasswordPostRequestFromJSON(json: any): ApiV1ResetPasswordPostRequest {
    return ApiV1ResetPasswordPostRequestFromJSONTyped(json, false);
}

export function ApiV1ResetPasswordPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ResetPasswordPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'email': json['email'],
        'password': json['password'],
        'passwordConfirmation': json['password_confirmation'],
    };
}

export function ApiV1ResetPasswordPostRequestToJSON(json: any): ApiV1ResetPasswordPostRequest {
    return ApiV1ResetPasswordPostRequestToJSONTyped(json, false);
}

export function ApiV1ResetPasswordPostRequestToJSONTyped(value?: ApiV1ResetPasswordPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'email': value['email'],
        'password': value['password'],
        'password_confirmation': value['passwordConfirmation'],
    };
}

