// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1RecoverPasswordPostRequest
 */
export interface ApiV1RecoverPasswordPostRequest {
    /**
     * User's email address
     * @type {string}
     * @memberof ApiV1RecoverPasswordPostRequest
     */
    email: string;
}

/**
 * Check if a given object implements the ApiV1RecoverPasswordPostRequest interface.
 */
export function instanceOfApiV1RecoverPasswordPostRequest(value: object): value is ApiV1RecoverPasswordPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ApiV1RecoverPasswordPostRequestFromJSON(json: any): ApiV1RecoverPasswordPostRequest {
    return ApiV1RecoverPasswordPostRequestFromJSONTyped(json, false);
}

export function ApiV1RecoverPasswordPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1RecoverPasswordPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ApiV1RecoverPasswordPostRequestToJSON(json: any): ApiV1RecoverPasswordPostRequest {
    return ApiV1RecoverPasswordPostRequestToJSONTyped(json, false);
}

export function ApiV1RecoverPasswordPostRequestToJSONTyped(value?: ApiV1RecoverPasswordPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

