// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1UsersIdGet200ResponseIncludedInner
 */
export interface ApiV1UsersIdGet200ResponseIncludedInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdGet200ResponseIncludedInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdGet200ResponseIncludedInner
     */
    type?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiV1UsersIdGet200ResponseIncludedInner
     */
    attributes?: object;
}

/**
 * Check if a given object implements the ApiV1UsersIdGet200ResponseIncludedInner interface.
 */
export function instanceOfApiV1UsersIdGet200ResponseIncludedInner(value: object): value is ApiV1UsersIdGet200ResponseIncludedInner {
    return true;
}

export function ApiV1UsersIdGet200ResponseIncludedInnerFromJSON(json: any): ApiV1UsersIdGet200ResponseIncludedInner {
    return ApiV1UsersIdGet200ResponseIncludedInnerFromJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UsersIdGet200ResponseIncludedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
    };
}

export function ApiV1UsersIdGet200ResponseIncludedInnerToJSON(json: any): ApiV1UsersIdGet200ResponseIncludedInner {
    return ApiV1UsersIdGet200ResponseIncludedInnerToJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseIncludedInnerToJSONTyped(value?: ApiV1UsersIdGet200ResponseIncludedInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': value['attributes'],
    };
}

