// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ClientsClientIdRegistriesGet200ResponseLinks
 */
export interface ApiV1ClientsClientIdRegistriesGet200ResponseLinks {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseLinks
     */
    first?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseLinks
     */
    last?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseLinks
     */
    prev?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ClientsClientIdRegistriesGet200ResponseLinks
     */
    next?: string;
}

/**
 * Check if a given object implements the ApiV1ClientsClientIdRegistriesGet200ResponseLinks interface.
 */
export function instanceOfApiV1ClientsClientIdRegistriesGet200ResponseLinks(value: object): value is ApiV1ClientsClientIdRegistriesGet200ResponseLinks {
    return true;
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseLinksFromJSON(json: any): ApiV1ClientsClientIdRegistriesGet200ResponseLinks {
    return ApiV1ClientsClientIdRegistriesGet200ResponseLinksFromJSONTyped(json, false);
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ClientsClientIdRegistriesGet200ResponseLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'prev': json['prev'] == null ? undefined : json['prev'],
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseLinksToJSON(json: any): ApiV1ClientsClientIdRegistriesGet200ResponseLinks {
    return ApiV1ClientsClientIdRegistriesGet200ResponseLinksToJSONTyped(json, false);
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseLinksToJSONTyped(value?: ApiV1ClientsClientIdRegistriesGet200ResponseLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first': value['first'],
        'last': value['last'],
        'prev': value['prev'],
        'next': value['next'],
    };
}

