// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1UsersIdGet200ResponseDataAttributes } from './ApiV1UsersIdGet200ResponseDataAttributes';
import {
    ApiV1UsersIdGet200ResponseDataAttributesFromJSON,
    ApiV1UsersIdGet200ResponseDataAttributesFromJSONTyped,
    ApiV1UsersIdGet200ResponseDataAttributesToJSON,
    ApiV1UsersIdGet200ResponseDataAttributesToJSONTyped,
} from './ApiV1UsersIdGet200ResponseDataAttributes';
import type { ApiV1UsersIdGet200ResponseDataRelationships } from './ApiV1UsersIdGet200ResponseDataRelationships';
import {
    ApiV1UsersIdGet200ResponseDataRelationshipsFromJSON,
    ApiV1UsersIdGet200ResponseDataRelationshipsFromJSONTyped,
    ApiV1UsersIdGet200ResponseDataRelationshipsToJSON,
    ApiV1UsersIdGet200ResponseDataRelationshipsToJSONTyped,
} from './ApiV1UsersIdGet200ResponseDataRelationships';

/**
 * 
 * @export
 * @interface ApiV1UsersIdGet200ResponseData
 */
export interface ApiV1UsersIdGet200ResponseData {
    /**
     * User ID
     * @type {string}
     * @memberof ApiV1UsersIdGet200ResponseData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UsersIdGet200ResponseData
     */
    type?: string;
    /**
     * 
     * @type {ApiV1UsersIdGet200ResponseDataAttributes}
     * @memberof ApiV1UsersIdGet200ResponseData
     */
    attributes?: ApiV1UsersIdGet200ResponseDataAttributes;
    /**
     * 
     * @type {ApiV1UsersIdGet200ResponseDataRelationships}
     * @memberof ApiV1UsersIdGet200ResponseData
     */
    relationships?: ApiV1UsersIdGet200ResponseDataRelationships;
}

/**
 * Check if a given object implements the ApiV1UsersIdGet200ResponseData interface.
 */
export function instanceOfApiV1UsersIdGet200ResponseData(value: object): value is ApiV1UsersIdGet200ResponseData {
    return true;
}

export function ApiV1UsersIdGet200ResponseDataFromJSON(json: any): ApiV1UsersIdGet200ResponseData {
    return ApiV1UsersIdGet200ResponseDataFromJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UsersIdGet200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'attributes': json['attributes'] == null ? undefined : ApiV1UsersIdGet200ResponseDataAttributesFromJSON(json['attributes']),
        'relationships': json['relationships'] == null ? undefined : ApiV1UsersIdGet200ResponseDataRelationshipsFromJSON(json['relationships']),
    };
}

export function ApiV1UsersIdGet200ResponseDataToJSON(json: any): ApiV1UsersIdGet200ResponseData {
    return ApiV1UsersIdGet200ResponseDataToJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseDataToJSONTyped(value?: ApiV1UsersIdGet200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'attributes': ApiV1UsersIdGet200ResponseDataAttributesToJSON(value['attributes']),
        'relationships': ApiV1UsersIdGet200ResponseDataRelationshipsToJSON(value['relationships']),
    };
}

