// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner } from './ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner';
import {
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSON,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSONTyped,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSON,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSONTyped,
} from './ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner';

/**
 * 
 * @export
 * @interface ApiV1UsersIdGet200ResponseDataRelationshipsClients
 */
export interface ApiV1UsersIdGet200ResponseDataRelationshipsClients {
    /**
     * 
     * @type {Array<ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner>}
     * @memberof ApiV1UsersIdGet200ResponseDataRelationshipsClients
     */
    data?: Array<ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner>;
}

/**
 * Check if a given object implements the ApiV1UsersIdGet200ResponseDataRelationshipsClients interface.
 */
export function instanceOfApiV1UsersIdGet200ResponseDataRelationshipsClients(value: object): value is ApiV1UsersIdGet200ResponseDataRelationshipsClients {
    return true;
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsClientsFromJSON(json: any): ApiV1UsersIdGet200ResponseDataRelationshipsClients {
    return ApiV1UsersIdGet200ResponseDataRelationshipsClientsFromJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsClientsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UsersIdGet200ResponseDataRelationshipsClients {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSON)),
    };
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsClientsToJSON(json: any): ApiV1UsersIdGet200ResponseDataRelationshipsClients {
    return ApiV1UsersIdGet200ResponseDataRelationshipsClientsToJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsClientsToJSONTyped(value?: ApiV1UsersIdGet200ResponseDataRelationshipsClients | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSON)),
    };
}

