// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SignInPost401Response
 */
export interface ApiV1SignInPost401Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SignInPost401Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ApiV1SignInPost401Response interface.
 */
export function instanceOfApiV1SignInPost401Response(value: object): value is ApiV1SignInPost401Response {
    return true;
}

export function ApiV1SignInPost401ResponseFromJSON(json: any): ApiV1SignInPost401Response {
    return ApiV1SignInPost401ResponseFromJSONTyped(json, false);
}

export function ApiV1SignInPost401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SignInPost401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ApiV1SignInPost401ResponseToJSON(json: any): ApiV1SignInPost401Response {
    return ApiV1SignInPost401ResponseToJSONTyped(json, false);
}

export function ApiV1SignInPost401ResponseToJSONTyped(value?: ApiV1SignInPost401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

