// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Client } from './Client';
import {
    ClientFromJSON,
    ClientFromJSONTyped,
    ClientToJSON,
    ClientToJSONTyped,
} from './Client';

/**
 * 
 * @export
 * @interface ApiV1ClientsPost201Response
 */
export interface ApiV1ClientsPost201Response {
    /**
     * 
     * @type {Client}
     * @memberof ApiV1ClientsPost201Response
     */
    data?: Client;
}

/**
 * Check if a given object implements the ApiV1ClientsPost201Response interface.
 */
export function instanceOfApiV1ClientsPost201Response(value: object): value is ApiV1ClientsPost201Response {
    return true;
}

export function ApiV1ClientsPost201ResponseFromJSON(json: any): ApiV1ClientsPost201Response {
    return ApiV1ClientsPost201ResponseFromJSONTyped(json, false);
}

export function ApiV1ClientsPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ClientsPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ClientFromJSON(json['data']),
    };
}

export function ApiV1ClientsPost201ResponseToJSON(json: any): ApiV1ClientsPost201Response {
    return ApiV1ClientsPost201ResponseToJSONTyped(json, false);
}

export function ApiV1ClientsPost201ResponseToJSONTyped(value?: ApiV1ClientsPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ClientToJSON(value['data']),
    };
}

