// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientRegistry } from './ClientRegistry';
import {
    ClientRegistryFromJSON,
    ClientRegistryFromJSONTyped,
    ClientRegistryToJSON,
    ClientRegistryToJSONTyped,
} from './ClientRegistry';
import type { ApiV1ClientsClientIdRegistriesGet200ResponseLinks } from './ApiV1ClientsClientIdRegistriesGet200ResponseLinks';
import {
    ApiV1ClientsClientIdRegistriesGet200ResponseLinksFromJSON,
    ApiV1ClientsClientIdRegistriesGet200ResponseLinksFromJSONTyped,
    ApiV1ClientsClientIdRegistriesGet200ResponseLinksToJSON,
    ApiV1ClientsClientIdRegistriesGet200ResponseLinksToJSONTyped,
} from './ApiV1ClientsClientIdRegistriesGet200ResponseLinks';
import type { ApiV1ClientsClientIdRegistriesGet200ResponseMeta } from './ApiV1ClientsClientIdRegistriesGet200ResponseMeta';
import {
    ApiV1ClientsClientIdRegistriesGet200ResponseMetaFromJSON,
    ApiV1ClientsClientIdRegistriesGet200ResponseMetaFromJSONTyped,
    ApiV1ClientsClientIdRegistriesGet200ResponseMetaToJSON,
    ApiV1ClientsClientIdRegistriesGet200ResponseMetaToJSONTyped,
} from './ApiV1ClientsClientIdRegistriesGet200ResponseMeta';

/**
 * 
 * @export
 * @interface ApiV1ClientsClientIdRegistriesGet200Response
 */
export interface ApiV1ClientsClientIdRegistriesGet200Response {
    /**
     * 
     * @type {Array<ClientRegistry>}
     * @memberof ApiV1ClientsClientIdRegistriesGet200Response
     */
    data?: Array<ClientRegistry>;
    /**
     * 
     * @type {ApiV1ClientsClientIdRegistriesGet200ResponseLinks}
     * @memberof ApiV1ClientsClientIdRegistriesGet200Response
     */
    links?: ApiV1ClientsClientIdRegistriesGet200ResponseLinks;
    /**
     * 
     * @type {ApiV1ClientsClientIdRegistriesGet200ResponseMeta}
     * @memberof ApiV1ClientsClientIdRegistriesGet200Response
     */
    meta?: ApiV1ClientsClientIdRegistriesGet200ResponseMeta;
}

/**
 * Check if a given object implements the ApiV1ClientsClientIdRegistriesGet200Response interface.
 */
export function instanceOfApiV1ClientsClientIdRegistriesGet200Response(value: object): value is ApiV1ClientsClientIdRegistriesGet200Response {
    return true;
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseFromJSON(json: any): ApiV1ClientsClientIdRegistriesGet200Response {
    return ApiV1ClientsClientIdRegistriesGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ClientsClientIdRegistriesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ClientRegistryFromJSON)),
        'links': json['links'] == null ? undefined : ApiV1ClientsClientIdRegistriesGet200ResponseLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ApiV1ClientsClientIdRegistriesGet200ResponseMetaFromJSON(json['meta']),
    };
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseToJSON(json: any): ApiV1ClientsClientIdRegistriesGet200Response {
    return ApiV1ClientsClientIdRegistriesGet200ResponseToJSONTyped(json, false);
}

export function ApiV1ClientsClientIdRegistriesGet200ResponseToJSONTyped(value?: ApiV1ClientsClientIdRegistriesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ClientRegistryToJSON)),
        'links': ApiV1ClientsClientIdRegistriesGet200ResponseLinksToJSON(value['links']),
        'meta': ApiV1ClientsClientIdRegistriesGet200ResponseMetaToJSON(value['meta']),
    };
}

