// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SignInPostRequest
 */
export interface ApiV1SignInPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SignInPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1SignInPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ApiV1SignInPostRequest interface.
 */
export function instanceOfApiV1SignInPostRequest(value: object): value is ApiV1SignInPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ApiV1SignInPostRequestFromJSON(json: any): ApiV1SignInPostRequest {
    return ApiV1SignInPostRequestFromJSONTyped(json, false);
}

export function ApiV1SignInPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SignInPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function ApiV1SignInPostRequestToJSON(json: any): ApiV1SignInPostRequest {
    return ApiV1SignInPostRequestToJSONTyped(json, false);
}

export function ApiV1SignInPostRequestToJSONTyped(value?: ApiV1SignInPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

