// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SignUpPostRequest
 */
export interface ApiV1SignUpPostRequest {
    /**
     * User's full name
     * @type {string}
     * @memberof ApiV1SignUpPostRequest
     */
    name: string;
    /**
     * User's email address
     * @type {string}
     * @memberof ApiV1SignUpPostRequest
     */
    email: string;
    /**
     * User's password
     * @type {string}
     * @memberof ApiV1SignUpPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ApiV1SignUpPostRequest interface.
 */
export function instanceOfApiV1SignUpPostRequest(value: object): value is ApiV1SignUpPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ApiV1SignUpPostRequestFromJSON(json: any): ApiV1SignUpPostRequest {
    return ApiV1SignUpPostRequestFromJSONTyped(json, false);
}

export function ApiV1SignUpPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SignUpPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function ApiV1SignUpPostRequestToJSON(json: any): ApiV1SignUpPostRequest {
    return ApiV1SignUpPostRequestToJSONTyped(json, false);
}

export function ApiV1SignUpPostRequestToJSONTyped(value?: ApiV1SignUpPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

