// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SignUpPost200ResponseDataMeta
 */
export interface ApiV1SignUpPost200ResponseDataMeta {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SignUpPost200ResponseDataMeta
     */
    accessToken?: string;
}

/**
 * Check if a given object implements the ApiV1SignUpPost200ResponseDataMeta interface.
 */
export function instanceOfApiV1SignUpPost200ResponseDataMeta(value: object): value is ApiV1SignUpPost200ResponseDataMeta {
    return true;
}

export function ApiV1SignUpPost200ResponseDataMetaFromJSON(json: any): ApiV1SignUpPost200ResponseDataMeta {
    return ApiV1SignUpPost200ResponseDataMetaFromJSONTyped(json, false);
}

export function ApiV1SignUpPost200ResponseDataMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SignUpPost200ResponseDataMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
    };
}

export function ApiV1SignUpPost200ResponseDataMetaToJSON(json: any): ApiV1SignUpPost200ResponseDataMeta {
    return ApiV1SignUpPost200ResponseDataMetaToJSONTyped(json, false);
}

export function ApiV1SignUpPost200ResponseDataMetaToJSONTyped(value?: ApiV1SignUpPost200ResponseDataMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
    };
}

