// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1UsersIdGet200ResponseDataRelationshipsClients } from './ApiV1UsersIdGet200ResponseDataRelationshipsClients';
import {
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsFromJSON,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsFromJSONTyped,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsToJSON,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsToJSONTyped,
} from './ApiV1UsersIdGet200ResponseDataRelationshipsClients';

/**
 * 
 * @export
 * @interface ApiV1UsersIdGet200ResponseDataRelationships
 */
export interface ApiV1UsersIdGet200ResponseDataRelationships {
    /**
     * 
     * @type {ApiV1UsersIdGet200ResponseDataRelationshipsClients}
     * @memberof ApiV1UsersIdGet200ResponseDataRelationships
     */
    clients?: ApiV1UsersIdGet200ResponseDataRelationshipsClients;
}

/**
 * Check if a given object implements the ApiV1UsersIdGet200ResponseDataRelationships interface.
 */
export function instanceOfApiV1UsersIdGet200ResponseDataRelationships(value: object): value is ApiV1UsersIdGet200ResponseDataRelationships {
    return true;
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsFromJSON(json: any): ApiV1UsersIdGet200ResponseDataRelationships {
    return ApiV1UsersIdGet200ResponseDataRelationshipsFromJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UsersIdGet200ResponseDataRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'clients': json['clients'] == null ? undefined : ApiV1UsersIdGet200ResponseDataRelationshipsClientsFromJSON(json['clients']),
    };
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsToJSON(json: any): ApiV1UsersIdGet200ResponseDataRelationships {
    return ApiV1UsersIdGet200ResponseDataRelationshipsToJSONTyped(json, false);
}

export function ApiV1UsersIdGet200ResponseDataRelationshipsToJSONTyped(value?: ApiV1UsersIdGet200ResponseDataRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clients': ApiV1UsersIdGet200ResponseDataRelationshipsClientsToJSON(value['clients']),
    };
}

