// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1SignUpPost200ResponseDataAttributes } from './ApiV1SignUpPost200ResponseDataAttributes';
import {
    ApiV1SignUpPost200ResponseDataAttributesFromJSON,
    ApiV1SignUpPost200ResponseDataAttributesFromJSONTyped,
    ApiV1SignUpPost200ResponseDataAttributesToJSON,
    ApiV1SignUpPost200ResponseDataAttributesToJSONTyped,
} from './ApiV1SignUpPost200ResponseDataAttributes';
import type { ApiV1SignUpPost200ResponseDataMeta } from './ApiV1SignUpPost200ResponseDataMeta';
import {
    ApiV1SignUpPost200ResponseDataMetaFromJSON,
    ApiV1SignUpPost200ResponseDataMetaFromJSONTyped,
    ApiV1SignUpPost200ResponseDataMetaToJSON,
    ApiV1SignUpPost200ResponseDataMetaToJSONTyped,
} from './ApiV1SignUpPost200ResponseDataMeta';

/**
 * 
 * @export
 * @interface ApiV1SignUpPost200ResponseData
 */
export interface ApiV1SignUpPost200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof ApiV1SignUpPost200ResponseData
     */
    type?: string;
    /**
     * User ID
     * @type {string}
     * @memberof ApiV1SignUpPost200ResponseData
     */
    id?: string;
    /**
     * 
     * @type {ApiV1SignUpPost200ResponseDataAttributes}
     * @memberof ApiV1SignUpPost200ResponseData
     */
    attributes?: ApiV1SignUpPost200ResponseDataAttributes;
    /**
     * 
     * @type {ApiV1SignUpPost200ResponseDataMeta}
     * @memberof ApiV1SignUpPost200ResponseData
     */
    meta?: ApiV1SignUpPost200ResponseDataMeta;
}

/**
 * Check if a given object implements the ApiV1SignUpPost200ResponseData interface.
 */
export function instanceOfApiV1SignUpPost200ResponseData(value: object): value is ApiV1SignUpPost200ResponseData {
    return true;
}

export function ApiV1SignUpPost200ResponseDataFromJSON(json: any): ApiV1SignUpPost200ResponseData {
    return ApiV1SignUpPost200ResponseDataFromJSONTyped(json, false);
}

export function ApiV1SignUpPost200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SignUpPost200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'attributes': json['attributes'] == null ? undefined : ApiV1SignUpPost200ResponseDataAttributesFromJSON(json['attributes']),
        'meta': json['meta'] == null ? undefined : ApiV1SignUpPost200ResponseDataMetaFromJSON(json['meta']),
    };
}

export function ApiV1SignUpPost200ResponseDataToJSON(json: any): ApiV1SignUpPost200ResponseData {
    return ApiV1SignUpPost200ResponseDataToJSONTyped(json, false);
}

export function ApiV1SignUpPost200ResponseDataToJSONTyped(value?: ApiV1SignUpPost200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'attributes': ApiV1SignUpPost200ResponseDataAttributesToJSON(value['attributes']),
        'meta': ApiV1SignUpPost200ResponseDataMetaToJSON(value['meta']),
    };
}

