// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner } from './ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner';
import {
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSON,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSONTyped,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSON,
    ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSONTyped,
} from './ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner';

/**
 * 
 * @export
 * @interface ClientRegistryRelationshipsClient
 */
export interface ClientRegistryRelationshipsClient {
    /**
     * 
     * @type {ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner}
     * @memberof ClientRegistryRelationshipsClient
     */
    data?: ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInner;
}

/**
 * Check if a given object implements the ClientRegistryRelationshipsClient interface.
 */
export function instanceOfClientRegistryRelationshipsClient(value: object): value is ClientRegistryRelationshipsClient {
    return true;
}

export function ClientRegistryRelationshipsClientFromJSON(json: any): ClientRegistryRelationshipsClient {
    return ClientRegistryRelationshipsClientFromJSONTyped(json, false);
}

export function ClientRegistryRelationshipsClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRegistryRelationshipsClient {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerFromJSON(json['data']),
    };
}

export function ClientRegistryRelationshipsClientToJSON(json: any): ClientRegistryRelationshipsClient {
    return ClientRegistryRelationshipsClientToJSONTyped(json, false);
}

export function ClientRegistryRelationshipsClientToJSONTyped(value?: ClientRegistryRelationshipsClient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ApiV1UsersIdGet200ResponseDataRelationshipsClientsDataInnerToJSON(value['data']),
    };
}

