// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientRelationshipsCityData } from './ClientRelationshipsCityData';
import {
    ClientRelationshipsCityDataFromJSON,
    ClientRelationshipsCityDataFromJSONTyped,
    ClientRelationshipsCityDataToJSON,
    ClientRelationshipsCityDataToJSONTyped,
} from './ClientRelationshipsCityData';

/**
 * 
 * @export
 * @interface ClientRelationshipsCity
 */
export interface ClientRelationshipsCity {
    /**
     * 
     * @type {ClientRelationshipsCityData}
     * @memberof ClientRelationshipsCity
     */
    data?: ClientRelationshipsCityData;
}

/**
 * Check if a given object implements the ClientRelationshipsCity interface.
 */
export function instanceOfClientRelationshipsCity(value: object): value is ClientRelationshipsCity {
    return true;
}

export function ClientRelationshipsCityFromJSON(json: any): ClientRelationshipsCity {
    return ClientRelationshipsCityFromJSONTyped(json, false);
}

export function ClientRelationshipsCityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRelationshipsCity {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ClientRelationshipsCityDataFromJSON(json['data']),
    };
}

export function ClientRelationshipsCityToJSON(json: any): ClientRelationshipsCity {
    return ClientRelationshipsCityToJSONTyped(json, false);
}

export function ClientRelationshipsCityToJSONTyped(value?: ClientRelationshipsCity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ClientRelationshipsCityDataToJSON(value['data']),
    };
}

