// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientRegistryRelationshipsUserData } from './ClientRegistryRelationshipsUserData';
import {
    ClientRegistryRelationshipsUserDataFromJSON,
    ClientRegistryRelationshipsUserDataFromJSONTyped,
    ClientRegistryRelationshipsUserDataToJSON,
    ClientRegistryRelationshipsUserDataToJSONTyped,
} from './ClientRegistryRelationshipsUserData';

/**
 * 
 * @export
 * @interface ClientRegistryRelationshipsUser
 */
export interface ClientRegistryRelationshipsUser {
    /**
     * 
     * @type {ClientRegistryRelationshipsUserData}
     * @memberof ClientRegistryRelationshipsUser
     */
    data?: ClientRegistryRelationshipsUserData;
}

/**
 * Check if a given object implements the ClientRegistryRelationshipsUser interface.
 */
export function instanceOfClientRegistryRelationshipsUser(value: object): value is ClientRegistryRelationshipsUser {
    return true;
}

export function ClientRegistryRelationshipsUserFromJSON(json: any): ClientRegistryRelationshipsUser {
    return ClientRegistryRelationshipsUserFromJSONTyped(json, false);
}

export function ClientRegistryRelationshipsUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRegistryRelationshipsUser {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ClientRegistryRelationshipsUserDataFromJSON(json['data']),
    };
}

export function ClientRegistryRelationshipsUserToJSON(json: any): ClientRegistryRelationshipsUser {
    return ClientRegistryRelationshipsUserToJSONTyped(json, false);
}

export function ClientRegistryRelationshipsUserToJSONTyped(value?: ClientRegistryRelationshipsUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ClientRegistryRelationshipsUserDataToJSON(value['data']),
    };
}

