// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientRegistryRelationshipsClientData
 */
export interface ClientRegistryRelationshipsClientData {
    /**
     * 
     * @type {string}
     * @memberof ClientRegistryRelationshipsClientData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientRegistryRelationshipsClientData
     */
    type?: string;
}

/**
 * Check if a given object implements the ClientRegistryRelationshipsClientData interface.
 */
export function instanceOfClientRegistryRelationshipsClientData(value: object): value is ClientRegistryRelationshipsClientData {
    return true;
}

export function ClientRegistryRelationshipsClientDataFromJSON(json: any): ClientRegistryRelationshipsClientData {
    return ClientRegistryRelationshipsClientDataFromJSONTyped(json, false);
}

export function ClientRegistryRelationshipsClientDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRegistryRelationshipsClientData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ClientRegistryRelationshipsClientDataToJSON(json: any): ClientRegistryRelationshipsClientData {
    return ClientRegistryRelationshipsClientDataToJSONTyped(json, false);
}

export function ClientRegistryRelationshipsClientDataToJSONTyped(value?: ClientRegistryRelationshipsClientData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

