// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientRegistryAttributes
 */
export interface ClientRegistryAttributes {
    /**
     * Registry title
     * @type {string}
     * @memberof ClientRegistryAttributes
     */
    title?: string;
    /**
     * Registry description
     * @type {string}
     * @memberof ClientRegistryAttributes
     */
    description?: string;
    /**
     * File attachment path
     * @type {string}
     * @memberof ClientRegistryAttributes
     */
    attachment?: string;
    /**
     * Client ID
     * @type {string}
     * @memberof ClientRegistryAttributes
     */
    clientId?: string;
    /**
     * User ID
     * @type {string}
     * @memberof ClientRegistryAttributes
     */
    userId?: string;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof ClientRegistryAttributes
     */
    createdAt?: Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof ClientRegistryAttributes
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ClientRegistryAttributes interface.
 */
export function instanceOfClientRegistryAttributes(value: object): value is ClientRegistryAttributes {
    return true;
}

export function ClientRegistryAttributesFromJSON(json: any): ClientRegistryAttributes {
    return ClientRegistryAttributesFromJSONTyped(json, false);
}

export function ClientRegistryAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRegistryAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'attachment': json['attachment'] == null ? undefined : json['attachment'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ClientRegistryAttributesToJSON(json: any): ClientRegistryAttributes {
    return ClientRegistryAttributesToJSONTyped(json, false);
}

export function ClientRegistryAttributesToJSONTyped(value?: ClientRegistryAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'attachment': value['attachment'],
        'client_id': value['clientId'],
        'user_id': value['userId'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

