// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientRelationshipsCity } from './ClientRelationshipsCity';
import {
    ClientRelationshipsCityFromJSON,
    ClientRelationshipsCityFromJSONTyped,
    ClientRelationshipsCityToJSON,
    ClientRelationshipsCityToJSONTyped,
} from './ClientRelationshipsCity';

/**
 * 
 * @export
 * @interface ClientRelationships
 */
export interface ClientRelationships {
    /**
     * 
     * @type {ClientRelationshipsCity}
     * @memberof ClientRelationships
     */
    city?: ClientRelationshipsCity;
}

/**
 * Check if a given object implements the ClientRelationships interface.
 */
export function instanceOfClientRelationships(value: object): value is ClientRelationships {
    return true;
}

export function ClientRelationshipsFromJSON(json: any): ClientRelationships {
    return ClientRelationshipsFromJSONTyped(json, false);
}

export function ClientRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRelationships {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : ClientRelationshipsCityFromJSON(json['city']),
    };
}

export function ClientRelationshipsToJSON(json: any): ClientRelationships {
    return ClientRelationshipsToJSONTyped(json, false);
}

export function ClientRelationshipsToJSONTyped(value?: ClientRelationships | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': ClientRelationshipsCityToJSON(value['city']),
    };
}

