// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientRegistryRelationshipsUserData
 */
export interface ClientRegistryRelationshipsUserData {
    /**
     * 
     * @type {string}
     * @memberof ClientRegistryRelationshipsUserData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientRegistryRelationshipsUserData
     */
    type?: string;
}

/**
 * Check if a given object implements the ClientRegistryRelationshipsUserData interface.
 */
export function instanceOfClientRegistryRelationshipsUserData(value: object): value is ClientRegistryRelationshipsUserData {
    return true;
}

export function ClientRegistryRelationshipsUserDataFromJSON(json: any): ClientRegistryRelationshipsUserData {
    return ClientRegistryRelationshipsUserDataFromJSONTyped(json, false);
}

export function ClientRegistryRelationshipsUserDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRegistryRelationshipsUserData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ClientRegistryRelationshipsUserDataToJSON(json: any): ClientRegistryRelationshipsUserData {
    return ClientRegistryRelationshipsUserDataToJSONTyped(json, false);
}

export function ClientRegistryRelationshipsUserDataToJSONTyped(value?: ClientRegistryRelationshipsUserData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

