// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * API Vizite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientRelationshipsCityData
 */
export interface ClientRelationshipsCityData {
    /**
     * 
     * @type {string}
     * @memberof ClientRelationshipsCityData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientRelationshipsCityData
     */
    type?: string;
}

/**
 * Check if a given object implements the ClientRelationshipsCityData interface.
 */
export function instanceOfClientRelationshipsCityData(value: object): value is ClientRelationshipsCityData {
    return true;
}

export function ClientRelationshipsCityDataFromJSON(json: any): ClientRelationshipsCityData {
    return ClientRelationshipsCityDataFromJSONTyped(json, false);
}

export function ClientRelationshipsCityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRelationshipsCityData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ClientRelationshipsCityDataToJSON(json: any): ClientRelationshipsCityData {
    return ClientRelationshipsCityDataToJSONTyped(json, false);
}

export function ClientRelationshipsCityDataToJSONTyped(value?: ClientRelationshipsCityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

